/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIFoo */

#ifndef _Included_JNIFoo
#define _Included_JNIFoo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIFoo
 * Method:    nativeFoo
 * Signature: ([CILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNIFoo_nativeFoo
  (JNIEnv *, jobject, jcharArray, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
